# Setup
title:            P D K Pavan Kumar
tagline:          'Web developer'
description:      'Web developer'
url:              https://pdkpavankumar.github.io/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
